name: nocterm_cli
description: CLI tools for nocterm - TUI framework for Dart
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  path: ^1.9.0
  nocterm:
    path: ../../

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
